#
# sd-boot: lib
#

#
# Source code
#
inc_dir += include_directories('.')

lib_sources += files(
  'cidr_parts.c', 
  'compare.c',
  'ip_address_range.c',
  'str_to_ip_addr.c',
  'ip_cidr_to_str.c',
  'cidr_is_subnet.c',
  'num_ips.c',
  'ip_address_increment.c',
  'range_to_cidrs.c',
  'range_to_cidrs_v4.c',
  'range_to_cidrs_v6.c',
  'cidr_to_range.c',
  'compact.c',
  'compact_v4.c',
  'compact_v6.c',
  'sort.c',
  'family_checks.c',
  'cidr_fix_host_bits.c',
  'exclude_cidrs.c',
  'set_prefix.c',
  'subnets_split.c',
  'clean_cidrs.c',
  'str_to_cidr_block.c',
  'cidr_host_bits.c',
  'cidr_contains_ip.c',
  'cidr_contains_cidr.c',
  'dns_ptr.c',
  'dns_forward.c',
  'cidrs.c',
  'split_by_family.c',
  'version.c',
  'str_array_to_cidrs.c',
  'flat_buffer_to_cidrs.c',
  'cidrs_to_flat_buffer.c',
  'sort_compare.c',
  'cidrs_intersection.c',
)

